#! /usr/bin/env fish

# Generate binary cache keys
if ! test -f ./cache-secret || ! test -f ./cache-public
    nix-store --generate-binary-cache-key nix-csi-cache-1 ./cache-secret ./cache-public
end
# Generate ssh keys
if ! test -f ./id_ed25519 || ! test -f ./id_ed25519.pub
    ssh-keygen -t ed25519 -f ./id_ed25519 -C nix-cache -N ""
end
# Build DaemonSet containerImage
nix run --file . imageToContainerd || begin
    echo "DaemonSet image failed"
    return 1
end
# Apply kubenix YAML
cat (CSITEST=1 nix build --file . manifestYAML) | kubectl apply -f -
