[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nix-csi"
version = "0.1.2"
description = "CSI driver populating mounts with /nix"
authors = [
    { name="Carl Andersson", email="carl@postspace.net" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = []

[project.scripts]
nix-csi = "nix_csi.cli:main"
