{
  kubenix,
  ...
}:
{
  imports = [
    kubenix.modules.k8s
    ./options.nix
    ./namespace.nix
    ./daemonset.nix
    ./crd.nix
    ./csidriver.nix
    ./storageclass.nix
    ./clusterRoleBinding.nix
    ./serviceAccount.nix
    ./customResourceAttrs.nix
    ./tmpDeploy.nix
  ];
}
